#!/usr/bin/bash
echo "                                                                                          "
echo "                                                                                          "
echo "                                     |     ====       ======    ===    ===    ======     |"
echo "                                     |	 ==  ==     ==        == =  = ==    ==  ==     |" 
echo "                                     |	 ==   ==    ====      ==  ==  ==    ==  ==     |"  
echo "                                     |	 ==  ==     ==        ==      ==    ==  ==     |"
echo "                                     |	 == =       ======    ==      ==    ======     |"
echo "                                      ___________________________________________________ "
echo "                                                                                          "
echo "                                                                                          "
echo "                                            WELCOME TO THE DEMO OF ONE-CLICK AUTOMATION   "
echo "                                                                     ---TEAM BASHERS---   "
echo "                                       ___________________________________________________"
echo "                                                                                          "
echo "                                                                                          "
echo "                                                                                          "
echo "                                        DEMO SCENARIO:                                    "
echo "                                       ---------------------------------------------------"
echo "                                       1. MOVING A LIVE ON-PREM APP TO GCP KUBERNETES     "
echo "                                          (GKE Cluster Exists already and details shared) "
echo "                                                                                          "
echo "                                       2. MOVING A LIVE ON-PREM APP TO AZURE KUBERNETES   "
echo "                                          (AKS Cluster doesn't exist and needs creation)  "
echo "                                                                                          "
echo "                                       3. MOVING A LIVE ON-PREM APP TO AWS EKS Cluster    "
echo "                                          (EKS Cluster Exists already and details shared) "
echo "                                                                                          "
echo "                                        UNDER-THE-HOOD SCENARIO:                          "
echo "                                       ---------------------------------------------------"
echo "                                       1. UNDERSTAND TECH STACK OF APP BEING MIGRATED     "
echo "                                       2. ASSESS SUITABILITY OF APP FOR CONTAINERIZATION  "
echo "                                                                                          "
echo "                                                                                          "
echo "                                                                                          "
echo " Press any Key to start:"
read tmp
echo " Enter the following details to start:"
echo " 1. Share basic configuration details about your App and Cloud Env. in the Properties file"
echo " Press any Key to open the configuration file...:"
read tmp
nano -l /c/Automation/SuperDemo/cspdotnet_apps.properties
echo " 2. The Path of your Source Code Repository for the Application you want to migrate.      "
echo "                                                                                          " 
echo " Your Source code Path.."
read appdir

#call the next routine
sh file_type_segregation.sh $appdir 

#clear
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "-------------------------------------------------------------------------------------------"
echo "                        THANKS FOR YOUR PATIENCE                                           "
echo "-------------------------------------------------------------------------------------------"